version: "2"
linters:
  enable:
    - bodyclose
    - containedctx
    - contextcheck
    - dogsled
    - durationcheck
    - errname
    - errorlint
    - forbidigo
    - loggercheck
    - misspell
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - unparam
    - wastedassign
    - whitespace
  disable:
    - errcheck
  settings:
    forbidigo:
      forbid:
        - pattern: ^print.*$
        - pattern: ^fmt\.Print.*$
          msg: Do not commit print statements.
        - pattern: fmt\.Print.*(# Do not commit print statements\.)?
      exclude-godoc-examples: false
      analyze-types: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
