version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "docker.io/driftive/driftive:{{ .Tag }}-amd64"
      - "docker.io/driftive/driftive:{{ .Major }}.{{ .Minor }}-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.description=Driftive"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "docker.io/driftive/driftive:{{ .Tag }}-arm64v8"
      - "docker.io/driftive/driftive:{{ .Major }}.{{ .Minor }}-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.description=Driftive"

docker_manifests:
  - name_template: "docker.io/driftive/driftive:{{ .Tag }}"
    image_templates:
      - docker.io/driftive/{{ .ProjectName }}:{{ .Tag }}-amd64
      - docker.io/driftive/{{ .ProjectName }}:{{ .Tag }}-arm64v8
  - name_template: "docker.io/driftive/driftive:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - docker.io/driftive/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-amd64
      - docker.io/driftive/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-arm64v8

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
